import { getChatGPTUser } from "@/app/chatgpt-auth";
import { emptyState,hydrateState } from "@/lib/summon";
import {loadOperationalState,saveOperationalState} from "@/db/state-repository";

export const dynamic="force-dynamic";
async function user(){const value=await getChatGPTUser();if(!value)throw new Error("UNAUTHORIZED");return value}
function assertState(value:any,previous:any,action?:string){
  if(!value||typeof value!=="object")throw new Error("Estado inválido");
  for(const key of ["materials","products","orders","productionOrders","lots","movements","payments","expenses"]){if(!Array.isArray(value[key]))throw new Error(`Coleção inválida: ${key}`);const ids=new Set<string>();for(const row of value[key]){if(!row?.id||ids.has(row.id))throw new Error(`ID inválido ou duplicado em ${key}`);ids.add(row.id)}}
  if(value.materials.some((x:any)=>Number(x.stockGrams)<0)||value.products.some((x:any)=>Number(x.readyStock)<0)||value.lots.some((x:any)=>Number(x.balance)<0||Number(x.balance)>Number(x.initialQuantity)))throw new Error("A operação resultaria em estoque inválido");
  if(value.expenses.some((x:any)=>Number(x.amount)<0)||value.payments.some((x:any)=>Number(x.expected)<0||Number(x.received)<0))throw new Error("Valor financeiro inválido");
  if(previous&&action!=="backup-import"){
    for(const old of previous.orders||[]){if(!["concluido","devolvido"].includes(old.status))continue;const next=value.orders.find((x:any)=>x.id===old.id);if(!next)throw new Error("Vendas históricas não podem ser excluídas");if(JSON.stringify(old.items)!==JSON.stringify(next.items)||old.gross!==next.gross||old.netRevenue!==next.netRevenue||old.cost!==next.cost||old.profit!==next.profit)throw new Error("Vendas concluídas são imutáveis");if(old.status==="devolvido"&&next.status!=="devolvido")throw new Error("Devoluções não podem ser reabertas")}
    for(const old of previous.productionOrders||[]){if(old.status!=="concluida")continue;const next=value.productionOrders.find((x:any)=>x.id===old.id);if(!next||JSON.stringify(old)!==JSON.stringify(next))throw new Error("Produções concluídas são imutáveis")}
  }
}
export async function GET(){try{const current=await user(),result=await loadOperationalState(current.userId),headers={"Cache-Control":"no-store, max-age=0"};if(!result)return Response.json({state:emptyState,version:0,local:true,storage:"browser"},{headers});return Response.json(result,{headers})}catch(error){const message=error instanceof Error?error.message:String(error);return Response.json({error:message},{status:message==="UNAUTHORIZED"?401:503,headers:{"Cache-Control":"no-store, max-age=0"}})}}
export async function PUT(request:Request){try{const current=await user(),body=await request.json() as {state:any;version:number;action?:string;entityType?:string;entityId?:string},existing=await loadOperationalState(current.userId);if(!existing)return Response.json({error:"Banco indisponível. Configure TURSO_DATABASE_URL e TURSO_AUTH_TOKEN na Vercel."},{status:503});const expected=Number(body.version)||0;if(existing.version!==expected)return Response.json({error:"Os dados foram atualizados em outra sessão. A versão mais recente foi carregada.",conflict:true,state:existing.state,version:existing.version},{status:409});const nextState=hydrateState(body.state);assertState(nextState,existing.state,body.action);const result=await saveOperationalState(current.userId,nextState,expected,body.action||"save",body.entityType,body.entityId);if(result.conflict&&"state" in result)return Response.json({error:"Os dados foram atualizados em outra sessão. A versão mais recente foi carregada.",conflict:true,state:result.state,version:result.version},{status:409});return Response.json({version:result.version,updatedAt:result.updatedAt})}catch(error){return Response.json({error:error instanceof Error?error.message:String(error)},{status:400})}}
