import { env } from "cloudflare:workers";
import { getChatGPTUser } from "@/app/chatgpt-auth";
import { emptyState } from "@/lib/summon";

export const dynamic="force-dynamic";
async function user(){const value=await getChatGPTUser();if(!value)throw new Error("UNAUTHORIZED");return value}
function assertState(value:any,previous:any,action?:string){
  if(!value||typeof value!=="object")throw new Error("Estado inválido");
  for(const key of ["materials","products","orders","productionOrders","lots","movements","payments","expenses"]){if(!Array.isArray(value[key]))throw new Error(`Coleção inválida: ${key}`);const ids=new Set<string>();for(const row of value[key]){if(!row?.id||ids.has(row.id))throw new Error(`ID inválido ou duplicado em ${key}`);ids.add(row.id)}}
  if(value.materials.some((x:any)=>Number(x.stockGrams)<0)||value.products.some((x:any)=>Number(x.readyStock)<0)||value.lots.some((x:any)=>Number(x.balance)<0||Number(x.balance)>Number(x.initialQuantity)))throw new Error("A operação resultaria em estoque inválido");
  if(value.expenses.some((x:any)=>Number(x.amount)<0)||value.payments.some((x:any)=>Number(x.expected)<0||Number(x.received)<0))throw new Error("Valor financeiro inválido");
  if(previous&&action!=="backup-import"){
    for(const old of previous.orders||[]){if(!["concluido","devolvido"].includes(old.status))continue;const next=value.orders.find((x:any)=>x.id===old.id);if(!next)throw new Error("Vendas históricas não podem ser excluídas");if(JSON.stringify(old.items)!==JSON.stringify(next.items)||old.gross!==next.gross||old.netRevenue!==next.netRevenue||old.cost!==next.cost||old.profit!==next.profit)throw new Error("Vendas concluídas são imutáveis");if(old.status==="devolvido"&&next.status!=="devolvido")throw new Error("Devoluções não podem ser reabertas")}
    for(const old of previous.productionOrders||[]){if(old.status!=="concluida")continue;const next=value.productionOrders.find((x:any)=>x.id===old.id);if(!next||JSON.stringify(old)!==JSON.stringify(next))throw new Error("Produções concluídas são imutáveis")}
  }
}
export async function GET(){try{const current=await user();if(!env.DB)return Response.json({state:emptyState,version:0,local:true});const row=await env.DB.prepare("SELECT payload, version FROM app_states WHERE user_id = ?").bind(current.userId).first<{payload:string;version:number}>();return Response.json(row?{state:JSON.parse(row.payload),version:row.version}:{state:emptyState,version:0})}catch(error){return Response.json({error:String(error)},{status:401})}}
export async function PUT(request:Request){try{const current=await user(),body=await request.json() as {state:any;version:number;action?:string;entityType?:string;entityId?:string};if(!env.DB)return Response.json({error:"Banco indisponível"},{status:503});const existing=await env.DB.prepare("SELECT version,payload FROM app_states WHERE user_id = ?").bind(current.userId).first<{version:number;payload:string}>(),expected=Number(body.version)||0;if((existing?.version||0)!==expected)return Response.json({error:"Os dados foram atualizados em outra sessão. A versão mais recente foi carregada.",conflict:true,state:existing?.payload?JSON.parse(existing.payload):emptyState,version:existing?.version||0},{status:409});const previous=existing?.payload?JSON.parse(existing.payload):null;assertState(body.state,previous,body.action);const next=expected+1,now=new Date().toISOString(),payload=JSON.stringify(body.state);if(payload.length>8_000_000)return Response.json({error:"Dados excedem o limite seguro"},{status:413});const write=env.DB.prepare("INSERT INTO app_states (user_id,version,payload,updated_at) VALUES (?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET version=excluded.version,payload=excluded.payload,updated_at=excluded.updated_at WHERE app_states.version=?").bind(current.userId,next,payload,now,expected),audit=env.DB.prepare("INSERT INTO audit_events (id,user_id,entity_type,entity_id,action,payload,created_at) VALUES (?,?,?,?,?,?,?)").bind(crypto.randomUUID(),current.userId,body.entityType||"state",body.entityId||current.userId,body.action||"save",JSON.stringify({version:next}),now);await env.DB.batch([write,audit]);return Response.json({version:next,updatedAt:now})}catch(error){return Response.json({error:error instanceof Error?error.message:String(error)},{status:400})}}
