CREATE TABLE IF NOT EXISTS suppliers (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, name TEXT NOT NULL, contact TEXT, email TEXT, status TEXT DEFAULT 'active' NOT NULL, snapshot TEXT DEFAULT '{}' NOT NULL);
CREATE TABLE IF NOT EXISTS purchase_records (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, material_id TEXT NOT NULL, supplier_id TEXT, weight_grams REAL NOT NULL, total_cents INTEGER NOT NULL, purchased_at TEXT NOT NULL, reversed_at TEXT, snapshot TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS recipe_versions (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, product_id TEXT NOT NULL, version INTEGER NOT NULL, snapshot TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_recipe_product_version ON recipe_versions (product_id, version);
CREATE TABLE IF NOT EXISTS machines (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, name TEXT NOT NULL, status TEXT NOT NULL, snapshot TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS maintenances (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, machine_id TEXT NOT NULL, cost_cents INTEGER NOT NULL, performed_at TEXT NOT NULL, snapshot TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS production_orders (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, number TEXT NOT NULL, product_id TEXT NOT NULL, recipe_version_id TEXT NOT NULL, status TEXT NOT NULL, snapshot TEXT NOT NULL, created_at TEXT NOT NULL, completed_at TEXT);
CREATE UNIQUE INDEX IF NOT EXISTS idx_production_user_number ON production_orders (user_id, number);
CREATE TABLE IF NOT EXISTS product_lots (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, code TEXT NOT NULL, product_id TEXT NOT NULL, production_order_id TEXT NOT NULL, balance INTEGER NOT NULL, unit_cost_cents INTEGER NOT NULL, produced_at TEXT NOT NULL, snapshot TEXT NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_lots_user_code ON product_lots (user_id, code);
CREATE TABLE IF NOT EXISTS customers (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, name TEXT NOT NULL, phone TEXT, email TEXT, city TEXT, state TEXT, snapshot TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS campaigns (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, name TEXT NOT NULL, platform TEXT NOT NULL, investment_cents INTEGER NOT NULL, status TEXT NOT NULL, snapshot TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS order_items (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, order_id TEXT NOT NULL, product_id TEXT NOT NULL, quantity INTEGER NOT NULL, revenue_cents INTEGER NOT NULL, cost_cents INTEGER NOT NULL, profit_cents INTEGER NOT NULL, snapshot TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS payments (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, order_id TEXT NOT NULL, expected_cents INTEGER NOT NULL, received_cents INTEGER NOT NULL, status TEXT NOT NULL, snapshot TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS goals (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, month TEXT NOT NULL, snapshot TEXT NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_goals_user_month ON goals (user_id, month);
CREATE INDEX IF NOT EXISTS idx_purchase_records_user_material ON purchase_records (user_id, material_id);
CREATE INDEX IF NOT EXISTS idx_production_orders_user_status ON production_orders (user_id, status);
CREATE INDEX IF NOT EXISTS idx_product_lots_user_product ON product_lots (user_id, product_id);
CREATE INDEX IF NOT EXISTS idx_customers_user_name ON customers (user_id, name);
CREATE INDEX IF NOT EXISTS idx_order_items_user_order ON order_items (user_id, order_id);
PRAGMA optimize;
