export type Channel = "direct" | "shopee" | "ml" | "other";
export type OrderStatus = "orcamento" | "aprovado" | "producao" | "pronto" | "enviado" | "concluido" | "cancelado" | "devolvido";
export type ProductionStatus = "planejada" | "aguardando_material" | "fila" | "imprimindo" | "acabamento" | "concluida" | "cancelada";
export type Settings = { energyRate:number; power:number; manualHourRate:number; machineValue:number; machineLife:number; markup:number; taxRate:number; packagingCost:number; maintenancePercent:number; minPrice:number; rounding:number; shopeeFee:number; shopeeFixed:number; mlFee:number; mlFixed:number };
export type Supplier = { id:string; name:string; contact:string; email:string; note:string; status:"active"|"archived" };
export type Material = { id:string; brand:string; type:string; color:string; unit:"kg"; supplierId?:string; location:string; stockGrams:number; averageCost:number; minimumGrams:number; status:"active"|"archived"; createdAt?:string };
export type MaterialPart = { materialId:string; name:string; weightGrams:number; costPerKg:number };
export type CostSnapshot = { material:number; energy:number; depreciation:number; labor:number; failure:number; maintenance:number; other:number; total:number; unitCost:number; directPrice:number; shopeePrice:number; mlPrice:number; directProfit:number; directMargin:number; settings:Settings };
export type RecipeVersion = { id:string; productId:string; version:number; parts:MaterialPart[]; wastePercent:number; failurePercent:number; printHours:number; manualHours:number; unitsPerPrint:number; snapshot:CostSnapshot; createdAt:string };
export type Product = { id:string; sku:string; name:string; description:string; category:string; universe:string; tags:string[]; dimensions:string; leadDays:number; imageUrl?:string; minimumStock:number; fulfillment:"hybrid"|"ready"|"made-to-order"; status:"active"|"paused"|"archived"; activeRecipeId:string; readyStock:number; snapshot:CostSnapshot; createdAt:string };
export type Purchase = { id:string; materialId:string; supplierId?:string; kg:number; subtotal:number; freight:number; total:number; date:string; note:string; reversedAt?:string };
export type Movement = { id:string; entity:"material"|"product"; entityId:string; kind:string; quantity:number; balanceAfter:number; referenceId?:string; unitCost?:number; note:string; createdAt:string };
export type Machine = { id:string; name:string; model:string; acquisitionValue:number; lifeHours:number; powerKw:number; accumulatedHours:number; status:"active"|"maintenance"|"archived"; lastMaintenance?:string };
export type Maintenance = { id:string; machineId:string; kind:"preventiva"|"corretiva"; cost:number; date:string; machineHours:number; note:string };
export type ProductionOrder = { id:string; number:string; productId:string; recipeVersionId:string; salesOrderId?:string; plannedQuantity:number; approvedQuantity:number; lostQuantity:number; priority:"baixa"|"normal"|"alta"; dueDate?:string; machineId?:string; status:ProductionStatus; plannedConsumption:MaterialPart[]; actualConsumption:MaterialPart[]; actualHours:number; lossReason:string; note:string; createdAt:string; completedAt?:string; lotId?:string };
export type ProductLot = { id:string; code:string; productId:string; productionOrderId:string; recipeVersionId:string; machineId?:string; initialQuantity:number; balance:number; unitCost:number; producedAt:string; note:string };
export type Customer = { id:string; name:string; phone:string; email:string; document:string; zip:string; city:string; state:string; address:string; origin:string; campaignId?:string; tags:string[]; note:string; consent:boolean; createdAt:string };
export type Campaign = { id:string; name:string; platform:string; startDate:string; endDate:string; investment:number; objective:string; target:string; note:string; status:"active"|"paused"|"finished" };
export type OrderItem = { id:string; productId:string; productName:string; productSku:string; category:string; universe:string; quantity:number; unitPrice:number; discount:number; revenue:number; cost:number; fees:number; taxes:number; adsAllocated:number; otherAllocated:number; profit:number; margin:number; lotAllocations:{lotId:string;quantity:number;unitCost:number}[] };
export type Order = { id:string; number:string; customerId?:string; customerName:string; channel:Channel; seller:string; items:OrderItem[]; status:OrderStatus; discount:number; fees:number; taxes:number; shippingCharged:number; shippingPaid:number; advertisingCost:number; otherCosts:number; paymentMethod:string; paymentStatus:"pendente"|"parcial"|"pago"|"estornado"; origin:string; campaignId?:string; addressSnapshot:string; note:string; gross:number; netRevenue:number; cost:number; profit:number; margin:number; stockAllocated?:boolean; stockApplied:boolean; productionOrderIds?:string[]; createdAt:string; completedAt?:string; returnedAt?:string };
export type Payment = { id:string; orderId:string; expected:number; received:number; dueDate:string; receivedAt?:string; method:string; status:"pendente"|"parcial"|"pago"|"estornado" };
export type Expense = { id:string; description:string; category:string; amount:number; dueDate:string; paidAt?:string; recurring:boolean; status:"pendente"|"pago"|"cancelado"; note:string; createdAt:string };
export type Goal = { id:string; month:string; revenue:number; profit:number; margin:number; production:number; sales:number; cac:number; roas:number };
export type Calculation = { id:string; name:string; weightGrams:number; wastePercent:number; snapshot:CostSnapshot; createdAt:string };
export type AppState = { settings:Settings; suppliers:Supplier[]; materials:Material[]; products:Product[]; recipes:RecipeVersion[]; purchases:Purchase[]; movements:Movement[]; machines:Machine[]; maintenances:Maintenance[]; productionOrders:ProductionOrder[]; lots:ProductLot[]; customers:Customer[]; campaigns:Campaign[]; orders:Order[]; payments:Payment[]; expenses:Expense[]; goals:Goal[]; calculations:Calculation[] };

export const defaults:Settings={energyRate:.95,power:.12,manualHourRate:25,machineValue:2500,machineLife:3000,markup:80,taxRate:0,packagingCost:0,maintenancePercent:3,minPrice:0,rounding:.1,shopeeFee:20,shopeeFixed:4,mlFee:17,mlFixed:0};
export const emptyState:AppState={settings:defaults,suppliers:[],materials:[],products:[],recipes:[],purchases:[],movements:[],machines:[],maintenances:[],productionOrders:[],lots:[],customers:[],campaigns:[],orders:[],payments:[],expenses:[],goals:[],calculations:[]};
export const uid=()=>crypto.randomUUID();
export const normalize=(value:string)=>String(value||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().replace(/\s+/g," ").toLowerCase();
export const money=(value:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(value||0);
export const cents=(value:number)=>Math.round(((Number(value)||0)+Number.EPSILON)*100)/100;
export const today=()=>new Date().toISOString().slice(0,10);

export function calculateCost(input:{parts:MaterialPart[];hours:number;manualHours:number;wastePercent:number;failurePercent:number;other:number;unitsPerPrint?:number},settings:Settings):CostSnapshot{
  const units=Math.max(1,input.unitsPerPrint||1),raw=input.parts.reduce((sum,p)=>sum+(p.weightGrams/1000)*(p.costPerKg||0),0),material=raw*(1+input.wastePercent/100),energy=input.hours*settings.power*settings.energyRate,depreciation=settings.machineLife?settings.machineValue/settings.machineLife*input.hours:0,labor=input.manualHours*settings.manualHourRate,maintenance=(depreciation+energy)*settings.maintenancePercent/100,base=material+energy+depreciation+labor+maintenance+input.other+settings.packagingCost*units,failure=base*input.failurePercent/100,total=cents(base+failure),unitCost=cents(total/units),target=unitCost*(1+settings.markup/100),tax=settings.taxRate/100,round=(v:number)=>Math.max(settings.minPrice,Math.ceil(v/Math.max(.01,settings.rounding))*Math.max(.01,settings.rounding)),channel=(fee:number,fixed:number)=>cents(round((target+fixed)/Math.max(.01,1-tax-fee/100))),directPrice=channel(0,0),shopeePrice=channel(settings.shopeeFee,settings.shopeeFixed),mlPrice=channel(settings.mlFee,settings.mlFixed),directProfit=cents(directPrice-unitCost),directMargin=directPrice?cents(directProfit/directPrice*100):0;
  return{material:cents(material),energy:cents(energy),depreciation:cents(depreciation),labor:cents(labor),failure:cents(failure),maintenance:cents(maintenance),other:cents(input.other+settings.packagingCost*units),total,unitCost,directPrice,shopeePrice,mlPrice,directProfit,directMargin,settings:{...settings}};
}

export function hydrateState(raw:any):AppState{
  const s={...emptyState,...raw,settings:{...defaults,...raw?.settings}} as AppState;
  s.expenses=s.expenses||[];
  s.products=(s.products||[]).map((p:any)=>({...p,description:p.description||"",dimensions:p.dimensions||"",leadDays:Number(p.leadDays)||0,minimumStock:Number(p.minimumStock)||0,activeRecipeId:p.activeRecipeId||"",snapshot:{maintenance:0,unitCost:p.snapshot?.total||0,directMargin:p.snapshot?.directPrice?cents((p.snapshot.directPrice-p.snapshot.total)/p.snapshot.directPrice*100):0,...p.snapshot}}));
  s.orders=(s.orders||[]).map((o:any)=>({...o,number:o.number||`PV-${String((s.orders||[]).indexOf(o)+1).padStart(4,"0")}`,customerName:o.customerName||o.customer||"Consumidor",items:o.items||[{id:uid(),productId:o.productId,productName:o.productName,productSku:o.productSku,category:o.category||"",universe:o.universe||"",quantity:o.quantity||1,unitPrice:o.quantity?o.gross/o.quantity:o.gross,discount:0,revenue:o.gross,cost:o.cost,fees:o.fees,taxes:o.taxes,adsAllocated:0,otherAllocated:0,profit:o.profit,margin:o.gross?cents(o.profit/o.gross*100):0,lotAllocations:[]}],discount:o.discount||0,shippingCharged:o.shippingCharged||0,shippingPaid:o.shippingPaid||0,advertisingCost:o.advertisingCost||0,otherCosts:o.otherCosts||0,paymentMethod:o.paymentMethod||"",paymentStatus:o.paymentStatus||"pendente",origin:o.origin||"",addressSnapshot:o.addressSnapshot||"",note:o.note||"",netRevenue:o.netRevenue??o.gross,margin:o.margin??(o.gross?cents(o.profit/o.gross*100):0),stockAllocated:Boolean(o.stockAllocated),productionOrderIds:o.productionOrderIds||[]}));
  return s;
}

export function recipeFor(state:AppState,product:Product){return state.recipes.find(r=>r.id===product.activeRecipeId)||state.recipes.filter(r=>r.productId===product.id).sort((a,b)=>b.version-a.version)[0]}
export function productStock(state:AppState,productId:string){return state.lots.filter(l=>l.productId===productId).reduce((s,l)=>s+l.balance,0)}

export const orderTransitions:Record<OrderStatus,OrderStatus[]>={
  orcamento:["aprovado","cancelado"],aprovado:["producao","pronto","cancelado"],producao:["pronto","cancelado"],pronto:["enviado","concluido","cancelado"],enviado:["concluido"],concluido:["devolvido"],cancelado:[],devolvido:[]
};

function allocateOrderStock(state:AppState,orderId:string){
  const order=state.orders.find(o=>o.id===orderId);if(!order)throw new Error("Pedido não encontrado");
  const required=new Map<string,number>();for(const item of order.items)required.set(item.productId,(required.get(item.productId)||0)+item.quantity);
  for(const [productId,quantity] of required){const product=state.products.find(p=>p.id===productId);if(!product||product.readyStock<quantity)throw new Error(`Estoque acabado insuficiente de ${product?.name||"produto"}`)}
  const lots=state.lots.map(l=>({...l})),products=state.products.map(p=>({...p})),movements=[...state.movements],now=new Date().toISOString();
  const items=order.items.map(item=>{let remaining=item.quantity;const lotAllocations:OrderItem["lotAllocations"]=[];for(const lot of lots.filter(l=>l.productId===item.productId&&l.balance>0).sort((a,b)=>a.producedAt.localeCompare(b.producedAt))){if(!remaining)break;const quantity=Math.min(remaining,lot.balance);lot.balance-=quantity;remaining-=quantity;lotAllocations.push({lotId:lot.id,quantity,unitCost:lot.unitCost})}if(remaining)throw new Error(`Lotes insuficientes de ${item.productName}`);const product=products.find(p=>p.id===item.productId)!;product.readyStock-=item.quantity;movements.push({id:uid(),entity:"product",entityId:item.productId,kind:"order-allocation",quantity:-item.quantity,balanceAfter:product.readyStock,referenceId:order.id,unitCost:lotAllocations.reduce((sum,a)=>sum+a.quantity*a.unitCost,0)/Math.max(1,item.quantity),note:`Separação ${order.number}`,createdAt:now});return{...item,lotAllocations}});
  return{...state,lots,products,movements,orders:state.orders.map(o=>o.id===order.id?{...o,items,status:"pronto" as const,stockAllocated:true}:o)};
}

function releaseOrderStock(state:AppState,orderId:string){
  const order=state.orders.find(o=>o.id===orderId);if(!order||!order.stockAllocated)return state;const lots=state.lots.map(l=>({...l})),products=state.products.map(p=>({...p})),movements=[...state.movements],now=new Date().toISOString();
  for(const item of order.items){for(const allocation of item.lotAllocations){const lot=lots.find(l=>l.id===allocation.lotId);if(lot)lot.balance+=allocation.quantity}const product=products.find(p=>p.id===item.productId);if(product){product.readyStock+=item.quantity;movements.push({id:uid(),entity:"product",entityId:item.productId,kind:"order-release",quantity:item.quantity,balanceAfter:product.readyStock,referenceId:order.id,unitCost:item.lotAllocations.reduce((sum,a)=>sum+a.quantity*a.unitCost,0)/Math.max(1,item.quantity),note:`Cancelamento ${order.number}`,createdAt:now})}}
  return{...state,lots,products,movements,orders:state.orders.map(o=>o.id===order.id?{...o,items:o.items.map(i=>({...i,lotAllocations:[]})),stockAllocated:false}:o)};
}

function planOrderShortages(state:AppState,orderId:string){
  const order=state.orders.find(o=>o.id===orderId);if(!order)throw new Error("Pedido não encontrado");const required=new Map<string,number>();for(const item of order.items)required.set(item.productId,(required.get(item.productId)||0)+item.quantity);
  const created:ProductionOrder[]=[];for(const [productId,quantity] of required){const product=state.products.find(p=>p.id===productId),shortage=Math.max(0,quantity-(product?.readyStock||0));if(!shortage)continue;if(!product)throw new Error("Produto do pedido não encontrado");const recipe=recipeFor(state,product);if(!recipe)throw new Error(`${product.name} não possui ficha técnica`);const factor=shortage/Math.max(1,recipe.unitsPerPrint),plannedConsumption=recipe.parts.map(p=>({...p,weightGrams:cents(p.weightGrams*factor*(1+recipe.wastePercent/100))}));created.push({id:uid(),number:`OP-${String(state.productionOrders.length+created.length+1).padStart(5,"0")}`,productId,recipeVersionId:recipe.id,salesOrderId:order.id,plannedQuantity:shortage,approvedQuantity:0,lostQuantity:0,priority:"alta",dueDate:undefined,status:"planejada",plannedConsumption,actualConsumption:[],actualHours:0,lossReason:"",note:`Gerada automaticamente para ${order.number} · ${order.customerName}`,createdAt:new Date().toISOString()})}
  if(!created.length)return allocateOrderStock(state,order.id);const productionOrderIds=[...(order.productionOrderIds||[]),...created.map(p=>p.id)];return{...state,productionOrders:[...state.productionOrders,...created],orders:state.orders.map(o=>o.id===order.id?{...o,status:"producao" as const,productionOrderIds}:o)};
}

export function approveOrder(state:AppState,orderId:string){const order=state.orders.find(o=>o.id===orderId);if(!order)throw new Error("Pedido não encontrado");if(order.status!=="orcamento")throw new Error("Somente pedidos em orçamento podem ser aprovados");return planOrderShortages(state,orderId)}

export function transitionOrder(state:AppState,orderId:string,status:OrderStatus){const order=state.orders.find(o=>o.id===orderId);if(!order)throw new Error("Pedido não encontrado");if(!orderTransitions[order.status].includes(status))throw new Error(`Não é possível passar de ${order.status} para ${status}`);if(status==="aprovado")return approveOrder(state,orderId);if(status==="cancelado"){const released=releaseOrderStock(state,orderId);return{...released,productionOrders:released.productionOrders.map(p=>p.salesOrderId===orderId&&!['concluida','cancelada'].includes(p.status)?{...p,status:"cancelada" as const}:p),orders:released.orders.map(o=>o.id===orderId?{...o,status:"cancelado" as const}:o)}}return{...state,orders:state.orders.map(o=>o.id===orderId?{...o,status}:o)}}

export function buildProduction(state:AppState,orderId:string,input:{approved:number;lost:number;hours:number;manualHours?:number;actualConsumption?:MaterialPart[];lossReason:string;note:string}){
  const po=state.productionOrders.find(x=>x.id===orderId);if(!po)throw new Error("Ordem não encontrada");if(po.status==="concluida")throw new Error("Ordem já concluída");
  const product=state.products.find(x=>x.id===po.productId),recipe=state.recipes.find(x=>x.id===po.recipeVersionId);if(!product||!recipe)throw new Error("Produto ou ficha técnica não encontrado");
  const totalUnits=Math.max(0,input.approved+input.lost),factor=totalUnits/Math.max(1,recipe.unitsPerPrint),planned=recipe.parts.map(p=>({...p,weightGrams:cents(p.weightGrams*factor*(1+recipe.wastePercent/100))})),consumption=(input.actualConsumption?.length?input.actualConsumption:planned).map(p=>({...p,weightGrams:cents(Math.max(0,p.weightGrams))}));
  for(const c of consumption){const m=state.materials.find(x=>x.id===c.materialId),label=c.name||(m?[m.type,m.color].filter(Boolean).join(" "):"insumo sem vínculo");if(!m)throw new Error(`Vincule ${label||"o insumo"} a um material do estoque antes de concluir`);if(m.stockGrams<c.weightGrams)throw new Error(`Estoque insuficiente de ${label}. Disponível: ${(m.stockGrams/1000).toFixed(3)} kg; necessário: ${(c.weightGrams/1000).toFixed(3)} kg`)}
  if(input.approved<=0)throw new Error("Informe ao menos uma unidade aprovada");
  const now=new Date().toISOString(),materials=state.materials.map(m=>{const c=consumption.find(x=>x.materialId===m.id);return c?{...m,stockGrams:cents(m.stockGrams-c.weightGrams)}:m}),materialCost=consumption.reduce((s,c)=>{const m=state.materials.find(x=>x.id===c.materialId);return s+c.weightGrams/1000*(m?.averageCost||c.costPerKg)},0),machine=state.machines.find(x=>x.id===po.machineId),settings={...recipe.snapshot.settings,power:machine?.powerKw||recipe.snapshot.settings.power,machineValue:machine?.acquisitionValue||recipe.snapshot.settings.machineValue,machineLife:machine?.lifeHours||recipe.snapshot.settings.machineLife},operational=calculateCost({parts:[],hours:input.hours,manualHours:input.manualHours??recipe.manualHours*factor,wastePercent:0,failurePercent:0,other:recipe.snapshot.other,unitsPerPrint:Math.max(1,input.approved)},settings),totalCost=cents(materialCost+operational.energy+operational.depreciation+operational.labor+operational.maintenance+operational.other),unitCost=cents(totalCost/Math.max(1,input.approved)),lotId=uid(),lot:ProductLot={id:lotId,code:`LT-${now.slice(0,10).replaceAll("-","")}-${state.lots.length+1}`,productId:product.id,productionOrderId:po.id,recipeVersionId:recipe.id,machineId:po.machineId,initialQuantity:input.approved,balance:input.approved,unitCost,producedAt:now,note:input.note},movements=[...state.movements];
  for(const c of consumption){const m=materials.find(x=>x.id===c.materialId)!;movements.push({id:uid(),entity:"material",entityId:c.materialId,kind:"production-consumption",quantity:-c.weightGrams,balanceAfter:m.stockGrams,referenceId:po.id,unitCost:m.averageCost,note:`Consumo ${po.number}`,createdAt:now})}
  movements.push({id:uid(),entity:"product",entityId:product.id,kind:"production",quantity:input.approved,balanceAfter:productStock(state,product.id)+input.approved,referenceId:po.id,unitCost,note:`Produção ${po.number}`,createdAt:now});
  const next={...state,materials,lots:[...state.lots,lot],movements,products:state.products.map(p=>p.id===product.id?{...p,readyStock:p.readyStock+input.approved}:p),machines:state.machines.map(m=>m.id===po.machineId?{...m,accumulatedHours:cents(m.accumulatedHours+input.hours)}:m),productionOrders:state.productionOrders.map(x=>x.id===po.id?{...x,approvedQuantity:input.approved,lostQuantity:input.lost,actualConsumption:consumption,actualHours:input.hours,lossReason:input.lossReason,note:input.note,status:"concluida" as const,completedAt:now,lotId}:x)} as AppState;
  if(po.salesOrderId){const salesOrder=next.orders.find(o=>o.id===po.salesOrderId),allCompleted=salesOrder?.productionOrderIds?.every(id=>next.productionOrders.find(p=>p.id===id)?.status==="concluida");if(allCompleted)return planOrderShortages(next,po.salesOrderId)}
  return next;
}

export function completeSale(state:AppState,orderId:string,advertisingCost:number){
  const order=state.orders.find(x=>x.id===orderId);if(!order)throw new Error("Pedido não encontrado");if(order.stockApplied)throw new Error("Venda já concluída");if(!orderTransitions[order.status].includes("concluido"))throw new Error("O pedido precisa estar pronto ou enviado antes da conclusão");let lots=state.lots.map(x=>({...x})),products=state.products.map(x=>({...x})),movements=[...state.movements],totalCost=0;const allocationsByItem=new Map<string,{lotId:string;quantity:number;unitCost:number}[]>();
  if(order.stockAllocated){for(const item of order.items){const allocs=item.lotAllocations||[];if(allocs.reduce((sum,a)=>sum+a.quantity,0)!==item.quantity)throw new Error(`Separação de estoque incompleta para ${item.productName}`);allocationsByItem.set(item.id,allocs);totalCost+=allocs.reduce((sum,a)=>sum+a.quantity*a.unitCost,0)}}else{for(const item of order.items){let remaining=item.quantity,allocs:OrderItem["lotAllocations"]=[];for(const lot of lots.filter(l=>l.productId===item.productId&&l.balance>0).sort((a,b)=>a.producedAt.localeCompare(b.producedAt))){if(!remaining)break;const qty=Math.min(remaining,lot.balance);lot.balance-=qty;remaining-=qty;totalCost+=qty*lot.unitCost;allocs.push({lotId:lot.id,quantity:qty,unitCost:lot.unitCost})}if(remaining>0)throw new Error(`Estoque insuficiente de ${item.productName}`);allocationsByItem.set(item.id,allocs);products=products.map(p=>p.id===item.productId?{...p,readyStock:p.readyStock-item.quantity}:p)}}
  const gross=cents(order.items.reduce((s,i)=>s+i.unitPrice*i.quantity,0)+order.shippingCharged),netRevenue=cents(gross-order.discount),channelFees=cents(order.fees),taxes=cents(order.taxes),shared=cents(advertisingCost+order.otherCosts+order.shippingPaid),basis=Math.max(.01,order.items.reduce((s,i)=>s+i.unitPrice*i.quantity-i.discount,0));
  const items=order.items.map(item=>{const revenue=cents(item.unitPrice*item.quantity-item.discount),ratio=revenue/basis,allocs=allocationsByItem.get(item.id)||[],cost=cents(allocs.reduce((s,a)=>s+a.quantity*a.unitCost,0)),fees=cents(channelFees*ratio),itemTaxes=cents(taxes*ratio),adsAllocated=cents(advertisingCost*ratio),otherAllocated=cents((order.otherCosts+order.shippingPaid)*ratio),profit=cents(revenue-fees-itemTaxes-cost-adsAllocated-otherAllocated),margin=revenue?cents(profit/revenue*100):0;return{...item,revenue,cost,fees,taxes:itemTaxes,adsAllocated,otherAllocated,profit,margin,lotAllocations:allocs}}),profit=cents(netRevenue-channelFees-taxes-totalCost-shared),margin=netRevenue?cents(profit/netRevenue*100):0,now=new Date().toISOString();
  if(!order.stockAllocated)for(const item of items){const balance=products.find(p=>p.id===item.productId)?.readyStock||0;movements.push({id:uid(),entity:"product",entityId:item.productId,kind:"sale",quantity:-item.quantity,balanceAfter:balance,referenceId:order.id,unitCost:item.quantity?item.cost/item.quantity:0,note:`Venda ${order.number}`,createdAt:now})}
  return{...state,lots,products,movements,orders:state.orders.map(o=>o.id===order.id?{...o,items,advertisingCost,gross,netRevenue,cost:cents(totalCost),profit,margin,status:"concluido" as const,stockApplied:true,completedAt:now}:o)};
}

export function returnSale(state:AppState,orderId:string){const order=state.orders.find(x=>x.id===orderId);if(!order||!order.stockApplied||order.status!=="concluido")throw new Error("Venda não concluída");const lots=state.lots.map(l=>({...l})),products=state.products.map(p=>({...p})),now=new Date().toISOString(),movements=[...state.movements];for(const item of order.items){for(const a of item.lotAllocations){const lot=lots.find(l=>l.id===a.lotId);if(lot)lot.balance+=a.quantity}const p=products.find(p=>p.id===item.productId);if(p)p.readyStock+=item.quantity;movements.push({id:uid(),entity:"product",entityId:item.productId,kind:"return",quantity:item.quantity,balanceAfter:p?.readyStock||0,referenceId:order.id,unitCost:item.quantity?item.cost/item.quantity:0,note:`Devolução ${order.number}`,createdAt:now})}return{...state,lots,products,movements,orders:state.orders.map(o=>o.id===order.id?{...o,status:"devolvido" as const,stockAllocated:false,stockApplied:false,returnedAt:now}:o),payments:state.payments.map(p=>p.orderId===order.id?{...p,status:"estornado" as const}:p)}}

export function migrateLegacy(raw:any):AppState{const now=new Date().toISOString(),base=hydrateState(raw?.materials?raw:emptyState);if(raw?.materials)return base;const materials=(raw.filaments||[]).map((f:any)=>({id:f.id||uid(),brand:f.brand||"Sem marca",type:f.type||"PLA",color:f.color||"Sem cor",unit:"kg" as const,location:"",stockGrams:Number(f.stockGrams)||0,averageCost:Number(f.avgCost??f.cost)||0,minimumGrams:Number(f.minimumStock)||250,status:f.status==="arquivado"?"archived" as const:"active" as const,createdAt:now}));return{...emptyState,settings:{...defaults,...raw.settings},materials};}
