export type Channel = "direct" | "shopee" | "ml";
export type OrderStatus = "orcamento" | "aprovado" | "producao" | "pronto" | "enviado" | "concluido" | "cancelado" | "devolvido";
export type Settings = { energyRate:number; power:number; manualHourRate:number; machineValue:number; machineLife:number; markup:number; taxRate:number; packagingCost:number; minPrice:number; rounding:number; shopeeFee:number; shopeeFixed:number; mlFee:number; mlFixed:number };
export type Material = { id:string; brand:string; type:string; color:string; stockGrams:number; averageCost:number; minimumGrams:number; status:"active"|"archived" };
export type MaterialPart = { materialId:string; name:string; weightGrams:number; costPerKg:number };
export type CostSnapshot = { material:number; energy:number; depreciation:number; labor:number; failure:number; other:number; total:number; directPrice:number; shopeePrice:number; mlPrice:number; directProfit:number; settings:Settings };
export type Product = { id:string; sku:string; name:string; category:string; universe:string; tags:string[]; imageUrl?:string; readyStock:number; minimumStock:number; fulfillment:"hybrid"|"ready"|"made-to-order"; status:"active"|"paused"|"archived"; parts:MaterialPart[]; wastePercent:number; snapshot:CostSnapshot; createdAt:string };
export type Purchase = { id:string; materialId:string; kg:number; total:number; date:string; note:string; reversedAt?:string };
export type Movement = { id:string; entity:"material"|"product"; entityId:string; kind:string; quantity:number; balanceAfter:number; note:string; createdAt:string };
export type Order = { id:string; productId:string; productName:string; productSku:string; category:string; universe:string; customer:string; channel:Channel; quantity:number; status:OrderStatus; gross:number; fees:number; taxes:number; cost:number; profit:number; stockApplied:boolean; createdAt:string };
export type Calculation = { id:string; name:string; weightGrams:number; wastePercent:number; snapshot:CostSnapshot; createdAt:string };
export type AppState = { settings:Settings; materials:Material[]; products:Product[]; purchases:Purchase[]; movements:Movement[]; orders:Order[]; calculations:Calculation[] };

export const defaults:Settings={energyRate:.95,power:.12,manualHourRate:25,machineValue:2500,machineLife:3000,markup:80,taxRate:0,packagingCost:0,minPrice:0,rounding:.1,shopeeFee:20,shopeeFixed:4,mlFee:17,mlFixed:0};
export const emptyState:AppState={settings:defaults,materials:[],products:[],purchases:[],movements:[],orders:[],calculations:[]};
export const uid=()=>crypto.randomUUID();
export const normalize=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().replace(/\s+/g," ").toLowerCase();
export const money=(value:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(value||0);
const cents=(value:number)=>Math.round((value+Number.EPSILON)*100)/100;
export function calculateCost(input:{parts:MaterialPart[];hours:number;manualHours:number;wastePercent:number;failurePercent:number;other:number},settings:Settings):CostSnapshot{
  const raw=input.parts.reduce((sum,p)=>sum+p.weightGrams/1000*p.costPerKg,0),material=raw*(1+input.wastePercent/100),energy=input.hours*settings.power*settings.energyRate,depreciation=settings.machineLife?settings.machineValue/settings.machineLife*input.hours:0,labor=input.manualHours*settings.manualHourRate,base=material+energy+depreciation+labor+input.other+settings.packagingCost,failure=base*input.failurePercent/100,total=cents(base+failure),target=total*(1+settings.markup/100),tax=settings.taxRate/100,round=(v:number)=>Math.max(settings.minPrice,Math.ceil(v/settings.rounding)*settings.rounding),channel=(fee:number,fixed:number)=>cents(round((target+fixed)/Math.max(.01,1-tax-fee/100))),directPrice=channel(0,0),shopeePrice=channel(settings.shopeeFee,settings.shopeeFixed),mlPrice=channel(settings.mlFee,settings.mlFixed);
  return{material:cents(material),energy:cents(energy),depreciation:cents(depreciation),labor:cents(labor),failure:cents(failure),other:cents(input.other+settings.packagingCost),total,directPrice,shopeePrice,mlPrice,directProfit:cents(directPrice-total),settings:{...settings}};
}
export function orderFinancials(product:Product,channel:Channel,quantity:number){const unit=channel==="direct"?product.snapshot.directPrice:channel==="shopee"?product.snapshot.shopeePrice:product.snapshot.mlPrice,gross=cents(unit*quantity),s=product.snapshot.settings,fees=cents(channel==="shopee"?(gross*s.shopeeFee/100+s.shopeeFixed*quantity):channel==="ml"?(gross*s.mlFee/100+s.mlFixed*quantity):0),taxes=cents(gross*s.taxRate/100),cost=cents(product.snapshot.total*quantity);return{gross,fees,taxes,cost,profit:cents(gross-fees-taxes-cost)}}
export function migrateLegacy(raw:any):AppState{const now=new Date().toISOString(),materials=(raw.filaments||[]).map((f:any,i:number)=>({id:f.id||uid(),brand:f.brand||"Sem marca",type:f.type||"PLA",color:f.color||"Sem cor",stockGrams:Number(f.stockGrams)||0,averageCost:Number(f.avgCost??f.cost)||0,minimumGrams:Number(f.minimumStock)||250,status:f.status==="arquivado"?"archived":"active"}));const materialByIndex=(i:number)=>materials[i];const products=(raw.products||[]).map((p:any,i:number)=>({id:p.id||uid(),sku:p.sku||`SUM-${String(i+1).padStart(4,"0")}`,name:p.name||"Produto",category:p.category||"Sem categoria",universe:p.universe||"",tags:Array.isArray(p.tags)?p.tags:[],imageUrl:p.photo?.startsWith("http")?p.photo:undefined,readyStock:Number(p.readyStock)||0,minimumStock:Number(p.minimumStock)||0,fulfillment:p.fulfillment==="sob-encomenda"?"made-to-order":p.fulfillment==="pronta-entrega"?"ready":"hybrid",status:p.status==="pausado"?"paused":"active",parts:(p.filaments||[]).map((x:any)=>({materialId:x.materialId||materialByIndex(x.materialIndex)?.id||"",name:x.name||"Material",weightGrams:Number(x.weight)||0,costPerKg:Number(x.costPerKg)||0})).filter((x:any)=>x.materialId),wastePercent:Number(p.waste)||0,snapshot:{material:Number(p.material)||0,energy:Number(p.energy)||0,depreciation:Number(p.depreciation)||0,labor:Number(p.labor)||0,failure:Number(p.failure)||0,other:Number(p.other)||0,total:Number(p.total)||0,directPrice:Number(p.directPrice)||0,shopeePrice:Number(p.shopeePrice)||0,mlPrice:Number(p.mlPrice)||0,directProfit:Number(p.profit)||0,settings:{...defaults,...p.settingsSnapshot,markup:Number(p.markup??p.settingsSnapshot?.margin??defaults.markup)}},createdAt:p.createdAt||now}));return{settings:{...defaults,...raw.settings,markup:Number(raw.settings?.markup??raw.settings?.margin??defaults.markup)},materials,products,purchases:(raw.purchases||[]).map((p:any)=>({id:p.id||uid(),materialId:p.materialId||"",kg:Number(p.kg)||0,total:Number(p.value)||0,date:p.date||now.slice(0,10),note:p.note||"",reversedAt:p.reversedAt})),movements:[],orders:[],calculations:[]}}
