// Used only by the Vercel/libSQL adapter. D1 schema changes remain owned by
// the versioned Drizzle migrations in /drizzle.
export const portableSchema = [
  "CREATE TABLE IF NOT EXISTS app_states (user_id TEXT PRIMARY KEY NOT NULL, version INTEGER NOT NULL DEFAULT 1, payload TEXT NOT NULL, updated_at TEXT NOT NULL)",
  "CREATE TABLE IF NOT EXISTS user_profiles (user_id TEXT PRIMARY KEY NOT NULL, version INTEGER NOT NULL DEFAULT 0, settings TEXT NOT NULL, write_token TEXT NOT NULL, legacy_migrated_at TEXT, updated_at TEXT NOT NULL)",
  "CREATE TABLE IF NOT EXISTS audit_events (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, action TEXT NOT NULL, payload TEXT NOT NULL, created_at TEXT NOT NULL)",
  "CREATE TABLE IF NOT EXISTS materials (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, brand TEXT NOT NULL, type TEXT NOT NULL, color TEXT NOT NULL, stock_grams REAL NOT NULL DEFAULT 0, average_cost REAL NOT NULL DEFAULT 0, minimum_grams REAL NOT NULL DEFAULT 250, status TEXT NOT NULL DEFAULT 'active', snapshot TEXT NOT NULL DEFAULT '{}')",
  "CREATE TABLE IF NOT EXISTS suppliers (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, name TEXT NOT NULL, contact TEXT, email TEXT, status TEXT NOT NULL DEFAULT 'active', snapshot TEXT NOT NULL DEFAULT '{}')",
  "CREATE TABLE IF NOT EXISTS purchase_records (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, material_id TEXT NOT NULL, supplier_id TEXT, weight_grams REAL NOT NULL, total_cents INTEGER NOT NULL, purchased_at TEXT NOT NULL, reversed_at TEXT, snapshot TEXT NOT NULL)",
  "CREATE TABLE IF NOT EXISTS products (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, sku TEXT NOT NULL, name TEXT NOT NULL, category TEXT NOT NULL, universe TEXT, tags TEXT NOT NULL DEFAULT '[]', ready_stock INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'active', snapshot TEXT NOT NULL)",
  "CREATE TABLE IF NOT EXISTS recipe_versions (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, product_id TEXT NOT NULL, version INTEGER NOT NULL, snapshot TEXT NOT NULL, created_at TEXT NOT NULL)",
  "CREATE TABLE IF NOT EXISTS recipe_components (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, recipe_version_id TEXT NOT NULL, material_id TEXT NOT NULL, weight_grams REAL NOT NULL, snapshot TEXT NOT NULL)",
  "CREATE TABLE IF NOT EXISTS machines (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, name TEXT NOT NULL, status TEXT NOT NULL, snapshot TEXT NOT NULL)",
  "CREATE TABLE IF NOT EXISTS maintenances (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, machine_id TEXT NOT NULL, cost_cents INTEGER NOT NULL, performed_at TEXT NOT NULL, snapshot TEXT NOT NULL)",
  "CREATE TABLE IF NOT EXISTS production_orders (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, number TEXT NOT NULL, product_id TEXT NOT NULL, recipe_version_id TEXT NOT NULL, status TEXT NOT NULL, snapshot TEXT NOT NULL, created_at TEXT NOT NULL, completed_at TEXT)",
  "CREATE TABLE IF NOT EXISTS product_lots (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, code TEXT NOT NULL, product_id TEXT NOT NULL, production_order_id TEXT NOT NULL, balance INTEGER NOT NULL, unit_cost_cents INTEGER NOT NULL, produced_at TEXT NOT NULL, snapshot TEXT NOT NULL)",
  "CREATE TABLE IF NOT EXISTS customers (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, name TEXT NOT NULL, phone TEXT, email TEXT, city TEXT, state TEXT, snapshot TEXT NOT NULL, created_at TEXT NOT NULL)",
  "CREATE TABLE IF NOT EXISTS campaigns (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, name TEXT NOT NULL, platform TEXT NOT NULL, investment_cents INTEGER NOT NULL, status TEXT NOT NULL, snapshot TEXT NOT NULL)",
  "CREATE TABLE IF NOT EXISTS orders (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, product_id TEXT NOT NULL, status TEXT NOT NULL, quantity INTEGER NOT NULL, channel TEXT NOT NULL, snapshot TEXT NOT NULL, created_at TEXT NOT NULL)",
  "CREATE TABLE IF NOT EXISTS order_items (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, order_id TEXT NOT NULL, product_id TEXT NOT NULL, quantity INTEGER NOT NULL, revenue_cents INTEGER NOT NULL, cost_cents INTEGER NOT NULL, profit_cents INTEGER NOT NULL, snapshot TEXT NOT NULL)",
  "CREATE TABLE IF NOT EXISTS movements (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, kind TEXT NOT NULL, quantity REAL NOT NULL, balance_after REAL NOT NULL, snapshot TEXT NOT NULL, created_at TEXT NOT NULL)",
  "CREATE TABLE IF NOT EXISTS payments (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, order_id TEXT NOT NULL, expected_cents INTEGER NOT NULL, received_cents INTEGER NOT NULL, status TEXT NOT NULL, snapshot TEXT NOT NULL)",
  "CREATE TABLE IF NOT EXISTS goals (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, month TEXT NOT NULL, snapshot TEXT NOT NULL)",
  "CREATE TABLE IF NOT EXISTS expenses (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, description TEXT NOT NULL, category TEXT NOT NULL, amount_cents INTEGER NOT NULL, due_date TEXT NOT NULL, paid_at TEXT, status TEXT NOT NULL, recurring INTEGER NOT NULL DEFAULT 0, snapshot TEXT NOT NULL, created_at TEXT NOT NULL)",
  "CREATE TABLE IF NOT EXISTS calculations (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, name TEXT NOT NULL, created_at TEXT NOT NULL, snapshot TEXT NOT NULL)",
  "CREATE UNIQUE INDEX IF NOT EXISTS idx_products_user_sku ON products (user_id, sku)",
  "CREATE UNIQUE INDEX IF NOT EXISTS idx_recipe_product_version ON recipe_versions (product_id, version)",
  "CREATE INDEX IF NOT EXISTS idx_orders_user_status_created ON orders (user_id, status, created_at)",
  "CREATE INDEX IF NOT EXISTS idx_movements_user_entity ON movements (user_id, entity_type, entity_id)",
  "CREATE INDEX IF NOT EXISTS idx_order_items_user_order ON order_items (user_id, order_id)",
  "CREATE INDEX IF NOT EXISTS idx_recipe_components_recipe ON recipe_components (user_id, recipe_version_id)",
  "CREATE INDEX IF NOT EXISTS idx_calculations_user_created ON calculations (user_id, created_at)",
];
