import { integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const appStates = sqliteTable("app_states", { userId: text("user_id").primaryKey(), version: integer("version").notNull().default(1), payload: text("payload").notNull(), updatedAt: text("updated_at").notNull() });
export const userProfiles = sqliteTable("user_profiles", { userId:text("user_id").primaryKey(), version:integer("version").notNull().default(0), settings:text("settings").notNull(), writeToken:text("write_token").notNull(), legacyMigratedAt:text("legacy_migrated_at"), updatedAt:text("updated_at").notNull() });
export const auditEvents = sqliteTable("audit_events", { id: text("id").primaryKey(), userId: text("user_id").notNull(), entityType: text("entity_type").notNull(), entityId: text("entity_id").notNull(), action: text("action").notNull(), payload: text("payload").notNull(), createdAt: text("created_at").notNull() });
export const images = sqliteTable("images", { id: text("id").primaryKey(), userId: text("user_id").notNull(), objectKey: text("object_key").notNull(), contentType: text("content_type").notNull(), size: integer("size").notNull(), createdAt: text("created_at").notNull() }, table => [uniqueIndex("idx_images_object_key").on(table.objectKey)]);
export const materials = sqliteTable("materials", { id: text("id").primaryKey(), userId: text("user_id").notNull(), brand: text("brand").notNull(), type: text("type").notNull(), color: text("color").notNull(), stockGrams: real("stock_grams").notNull().default(0), averageCost: real("average_cost").notNull().default(0), minimumGrams: real("minimum_grams").notNull().default(250), status: text("status").notNull().default("active"), snapshot:text("snapshot").notNull().default("{}") });
export const products = sqliteTable("products", { id: text("id").primaryKey(), userId: text("user_id").notNull(), sku: text("sku").notNull(), name: text("name").notNull(), category: text("category").notNull(), universe: text("universe"), tags: text("tags").notNull().default("[]"), readyStock: integer("ready_stock").notNull().default(0), status: text("status").notNull().default("active"), snapshot: text("snapshot").notNull() }, table => [uniqueIndex("idx_products_user_sku").on(table.userId, table.sku)]);
export const orders = sqliteTable("orders", { id: text("id").primaryKey(), userId: text("user_id").notNull(), productId: text("product_id").notNull(), status: text("status").notNull(), quantity: integer("quantity").notNull(), channel: text("channel").notNull(), snapshot: text("snapshot").notNull(), createdAt: text("created_at").notNull() });
export const movements = sqliteTable("movements", { id: text("id").primaryKey(), userId: text("user_id").notNull(), entityType: text("entity_type").notNull(), entityId: text("entity_id").notNull(), kind: text("kind").notNull(), quantity: real("quantity").notNull(), balanceAfter: real("balance_after").notNull(), snapshot: text("snapshot").notNull(), createdAt: text("created_at").notNull() });

export const suppliers = sqliteTable("suppliers", { id:text("id").primaryKey(), userId:text("user_id").notNull(), name:text("name").notNull(), contact:text("contact"), email:text("email"), status:text("status").notNull().default("active"), snapshot:text("snapshot").notNull().default("{}") });
export const purchases = sqliteTable("purchase_records", { id:text("id").primaryKey(), userId:text("user_id").notNull(), materialId:text("material_id").notNull(), supplierId:text("supplier_id"), weightGrams:real("weight_grams").notNull(), totalCents:integer("total_cents").notNull(), purchasedAt:text("purchased_at").notNull(), reversedAt:text("reversed_at"), snapshot:text("snapshot").notNull() });
export const recipeVersions = sqliteTable("recipe_versions", { id:text("id").primaryKey(), userId:text("user_id").notNull(), productId:text("product_id").notNull(), version:integer("version").notNull(), snapshot:text("snapshot").notNull(), createdAt:text("created_at").notNull() }, table=>[uniqueIndex("idx_recipe_product_version").on(table.productId,table.version)]);
export const machines = sqliteTable("machines", { id:text("id").primaryKey(), userId:text("user_id").notNull(), name:text("name").notNull(), status:text("status").notNull(), snapshot:text("snapshot").notNull() });
export const maintenances = sqliteTable("maintenances", { id:text("id").primaryKey(), userId:text("user_id").notNull(), machineId:text("machine_id").notNull(), costCents:integer("cost_cents").notNull(), performedAt:text("performed_at").notNull(), snapshot:text("snapshot").notNull() });
export const productionOrders = sqliteTable("production_orders", { id:text("id").primaryKey(), userId:text("user_id").notNull(), number:text("number").notNull(), productId:text("product_id").notNull(), recipeVersionId:text("recipe_version_id").notNull(), status:text("status").notNull(), snapshot:text("snapshot").notNull(), createdAt:text("created_at").notNull(), completedAt:text("completed_at") }, table=>[uniqueIndex("idx_production_user_number").on(table.userId,table.number)]);
export const productLots = sqliteTable("product_lots", { id:text("id").primaryKey(), userId:text("user_id").notNull(), code:text("code").notNull(), productId:text("product_id").notNull(), productionOrderId:text("production_order_id").notNull(), balance:integer("balance").notNull(), unitCostCents:integer("unit_cost_cents").notNull(), producedAt:text("produced_at").notNull(), snapshot:text("snapshot").notNull() }, table=>[uniqueIndex("idx_lots_user_code").on(table.userId,table.code)]);
export const customers = sqliteTable("customers", { id:text("id").primaryKey(), userId:text("user_id").notNull(), name:text("name").notNull(), phone:text("phone"), email:text("email"), city:text("city"), state:text("state"), snapshot:text("snapshot").notNull(), createdAt:text("created_at").notNull() });
export const campaigns = sqliteTable("campaigns", { id:text("id").primaryKey(), userId:text("user_id").notNull(), name:text("name").notNull(), platform:text("platform").notNull(), investmentCents:integer("investment_cents").notNull(), status:text("status").notNull(), snapshot:text("snapshot").notNull() });
export const orderItems = sqliteTable("order_items", { id:text("id").primaryKey(), userId:text("user_id").notNull(), orderId:text("order_id").notNull(), productId:text("product_id").notNull(), quantity:integer("quantity").notNull(), revenueCents:integer("revenue_cents").notNull(), costCents:integer("cost_cents").notNull(), profitCents:integer("profit_cents").notNull(), snapshot:text("snapshot").notNull() });
export const payments = sqliteTable("payments", { id:text("id").primaryKey(), userId:text("user_id").notNull(), orderId:text("order_id").notNull(), expectedCents:integer("expected_cents").notNull(), receivedCents:integer("received_cents").notNull(), status:text("status").notNull(), snapshot:text("snapshot").notNull() });
export const goals = sqliteTable("goals", { id:text("id").primaryKey(), userId:text("user_id").notNull(), month:text("month").notNull(), snapshot:text("snapshot").notNull() }, table=>[uniqueIndex("idx_goals_user_month").on(table.userId,table.month)]);
export const expenses = sqliteTable("expenses", { id:text("id").primaryKey(), userId:text("user_id").notNull(), description:text("description").notNull(), category:text("category").notNull(), amountCents:integer("amount_cents").notNull(), dueDate:text("due_date").notNull(), paidAt:text("paid_at"), status:text("status").notNull(), recurring:integer("recurring",{mode:"boolean"}).notNull().default(false), snapshot:text("snapshot").notNull(), createdAt:text("created_at").notNull() });
export const calculations = sqliteTable("calculations", { id:text("id").primaryKey(), userId:text("user_id").notNull(), name:text("name").notNull(), createdAt:text("created_at").notNull(), snapshot:text("snapshot").notNull() });
export const recipeComponents = sqliteTable("recipe_components", { id:text("id").primaryKey(), userId:text("user_id").notNull(), recipeVersionId:text("recipe_version_id").notNull(), materialId:text("material_id").notNull(), weightGrams:real("weight_grams").notNull(), snapshot:text("snapshot").notNull() });
