import { integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const appStates = sqliteTable("app_states", { userId: text("user_id").primaryKey(), version: integer("version").notNull().default(1), payload: text("payload").notNull(), updatedAt: text("updated_at").notNull() });
export const auditEvents = sqliteTable("audit_events", { id: text("id").primaryKey(), userId: text("user_id").notNull(), entityType: text("entity_type").notNull(), entityId: text("entity_id").notNull(), action: text("action").notNull(), payload: text("payload").notNull(), createdAt: text("created_at").notNull() });
export const images = sqliteTable("images", { id: text("id").primaryKey(), userId: text("user_id").notNull(), objectKey: text("object_key").notNull(), contentType: text("content_type").notNull(), size: integer("size").notNull(), createdAt: text("created_at").notNull() }, table => [uniqueIndex("idx_images_object_key").on(table.objectKey)]);
export const materials = sqliteTable("materials", { id: text("id").primaryKey(), userId: text("user_id").notNull(), brand: text("brand").notNull(), type: text("type").notNull(), color: text("color").notNull(), stockGrams: real("stock_grams").notNull().default(0), averageCost: real("average_cost").notNull().default(0), minimumGrams: real("minimum_grams").notNull().default(250), status: text("status").notNull().default("active") });
export const products = sqliteTable("products", { id: text("id").primaryKey(), userId: text("user_id").notNull(), sku: text("sku").notNull(), name: text("name").notNull(), category: text("category").notNull(), universe: text("universe"), tags: text("tags").notNull().default("[]"), readyStock: integer("ready_stock").notNull().default(0), status: text("status").notNull().default("active"), snapshot: text("snapshot").notNull() }, table => [uniqueIndex("idx_products_user_sku").on(table.userId, table.sku)]);
export const orders = sqliteTable("orders", { id: text("id").primaryKey(), userId: text("user_id").notNull(), productId: text("product_id").notNull(), status: text("status").notNull(), quantity: integer("quantity").notNull(), channel: text("channel").notNull(), snapshot: text("snapshot").notNull(), createdAt: text("created_at").notNull() });
export const movements = sqliteTable("movements", { id: text("id").primaryKey(), userId: text("user_id").notNull(), entityType: text("entity_type").notNull(), entityId: text("entity_id").notNull(), kind: text("kind").notNull(), quantity: real("quantity").notNull(), balanceAfter: real("balance_after").notNull(), snapshot: text("snapshot").notNull(), createdAt: text("created_at").notNull() });
